name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Verificar se o projeto contém arquivos HTML
        run: |
          if ! find . -name "*.html" -print -quit | grep -q .; then
            echo "Erro: O projeto não contém arquivos HTML."
            exit 1
          fi

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instalar dependências
        run: npm install

      - name: Testar o projeto
        run: npm test

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Verificar integridade dos arquivos do projeto
        run: |
          if ! git diff --quiet; then
            echo "Erro: O projeto possui arquivos modificados."
            exit 1
          fi
