name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instalar dependências
        run: npm install

      - name: Construir o projeto
        run: npm run build

      - name: Testar o projeto
        run: npm test

      - name: Implantação
        run: |
          